---
- block:
    - name: generate Geo-rep session specific ssh-keys
      command: "gluster system:: execute gsec_create"
      args:
        creates: /var/lib/glusterd/geo-replication/common_secret.pem.pub
      when: inventory_hostname == groups['gluster-primary'][0] or
            inventory_hostname == groups['gluster-backup'][0]

    - name: Setup shared storage volume
      command: gluster volume set all cluster.enable-shared-storage enable
      when: inventory_hostname == groups['gluster-primary'][0] or
            inventory_hostname == groups['gluster-backup'][0]
      ignore_errors: true

    - name: Enable glusterfssharedstorage service
      systemd: 
        name: glusterfssharedstorage
        enabled: yes
        state: started
  
    - name: Disable performace.quick-read on slave volume
      command: gluster volume set "{{ item }}" performance.quick-read off
      with_items: "{{ slave_vols }}"
      when: inventory_hostname == groups['gluster-backup'][0]

    - name: Set slave volume to read-only
      command: gluster volume set "{{ item }}" features.read-only on
      with_items: "{{ slave_vols }}"
      when: inventory_hostname == groups['gluster-backup'][0]
  become: yes

