---
- name: Create Geo-Replication session from Secondary to Primary
  command: "gluster volume geo-replication {{ slave_vols }} gluster01.example.com::{{ master_vols }} create push-pem force"

- name: Config meta volume
  command: "gluster volume geo-replication {{ slave_vols }} gluster01.example.com::{{ master_vols }} config use_meta_volume true"

- name: Config special sync mode for recovery
  command: "gluster volume geo-replication {{ slave_vols }} gluster01.example.com::{{ master_vols }} config special-sync-mode recover"

#- name: Disable the gfid-conflict-resolution option
#  command: "gluster volume geo-replication {{ slave_vols }} gluster01.example.com::{{ master_vols }} config gfid-conflict-resolution false"

- name: Start Geo-Replication session
  command: "gluster volume geo-replication {{ slave_vols }} gluster01.example.com::{{ master_vols }} start"


