---
- hosts: gluster-primary[0]
  vars:
    ansible_user: root
 
  tasks:
    - name: Stop geo-replication
      command: python /usr/share/glusterfs/scripts/schedule_georep.py rhv-sd1 dr-gluster01.example.com rhv-sd1-dr

- hosts: gluster-primary
  vars:
    ansible_user: root
 
  tasks:
    - name: Stop glusterd to simulate failure
      systemd:
        state: stopped
        name: glusterd

    - name: Kill running glusterfs processes
      command: pkill glusterfs

- hosts: rhvm.example.com
  vars:
    ansible_user: root
  
  tasks:
    - name: Stop ovirt-engine
      systemd:
        state: stopped
        name: ovirt-engine
