---
- hosts: gluster-primary
  vars:
    ansible_user: root
 
  tasks:
    - name: Start glusterd
      systemd:
        state: started
        name: glusterd

    - name: Restart glusterfssharedstorage service
      systemd:
        state: restarted
        name: glusterfssharedstorage


#- hosts: gluster-primary[0]
#  vars:
#    ansible_user: root
# 
#  tasks:
#    - name: Start geo-replication
#      command: gluster volume geo-replication rhv-sd1 10.200.0.81::rhv-sd1-dr start

- hosts: rhvm.example.com
  vars:
    ansible_user: root
  
  tasks:
    - name: Start ovirt-engine
      systemd:
        state: started
        name: ovirt-engine

