---
- hosts: gluster-primary
  vars: 
    ansible_user: root

  tasks:
  - name: Ensure Gluster is running on primary site
    systemd:
      state: started
      name: glusterd
    tags: clean_engine

- hosts: gluster-primary[0]
  vars: 
    ansible_user: root

  tasks:
  - name: Stop Geo Replication from Primary to Secondary
    import_role:
      name: gluster
      tasks_from: stop-primary-georep.yml
    tags: clean_engine

