---
- hosts: gluster-backup[0]
  vars: 
    ansible_user: root

  tasks:
  - name: Failback storage
    import_role:
      name: gluster
      tasks_from: failback.yml
    tags: fail_back

- hosts: gluster-primary[0]
  vars: 
    ansible_user: root

  tasks:
  - name: Set volume to read-write
    command: gluster volume set {{ master_vols }} features.read-only off
    tags: fail_back


- hosts: rhvh-primary[0]
  tags:
    - fail_back
  vars: 
    ansible_user: root
    share_path: gluster01.example.com:/data

  tasks:
  - name: Release SD locks (only for demo)
    import_role:
      name: gluster
      tasks_from: release_lock.yml


