---
- hosts: gluster-secondary[0]
  vars: 
    ansible_user: root

  tasks:
  - name: Failback storage
    import_role:
      name: gluster
      tasks_from: failback.yml
    tags: fail_back

- hosts: gluster-primary[0]
  vars: 
    ansible_user: root

  tasks:
  - name: Set volume to read-write
    command: gluster volume set rhv-sd1 features.read-only off
    tags: fail_back


#- hosts: rhvh-primary[0]
#  tags:
#    - fail_over 
#  vars: 
#    ansible_user: root
#    share_path: gluster01.example.com:/rhv-sd1
#
#  tasks:
#  - name: Release SD locks (only for demo)
#    import_role:
#      name: gluster
#      tasks_from: release_lock.yml
#

