---
- hosts: ovirt-hosts-backup[0]
  become: yes
  tags:
    - fail_over 
  vars: 
    ansible_user: admin
    share_path: dr-gluster01.example.com:/data

  tasks:
  - name: Release SD locks (only for demo)
    import_role:
      name: gluster
      tasks_from: release_lock.yml

- hosts: gluster-backup[0]
  become: yes
  tags:
    - fail_over 
  vars: 
    ansible_user: admin

  tasks:
  - name: Gluster tasks
    import_role:
      name: gluster
      tasks_from: failover.yml

