---
- hosts: gluster-backup[0]
  become: yes
  vars: 
    ansible_user: admin

  tasks:
  - name: Failback storage
    import_role:
      name: gluster
      tasks_from: failback.yml
    tags: fail_back

- hosts: gluster-primary[0]
  become: yes
  vars: 
    ansible_user: admin

  tasks:
  - name: Set volume to read-write
    command: gluster volume set {{ item }} features.read-only off
    loop: "{{ master_vols|flatten(levels=1) }}"
    tags: fail_back


- hosts: ovirt-hosts-primary[0]
  become: yes
  tags:
    - fail_back
  vars: 
    ansible_user: admin
    share_path: gluster01.example.com:/data

  tasks:
  - name: Release SD locks (only for demo)
    import_role:
      name: gluster
      tasks_from: release_lock.yml


