---
- hosts: gluster-secondary[0]
  tags:
    - fail_over 
  vars: 
    ansible_user: root

  tasks:
  - name: Gluster tasks
    import_role:
      name: gluster
      tasks_from: failover.yml

  - name: Ensure locks are released (pause)
    pause: 
      minutes: 1
