---
- hosts: gluster-primary,gluster-backup
  become: yes
  vars:
    ansible_user: admin

  tasks:
    - import_role:
        name: gluster
        tasks_from: configure-georep.yml

- hosts: gluster-primary[0]
  become: yes
  vars:
    ansible_user: admin

  tasks:
    - import_role:
        name: gluster
        tasks_from: create-georep-session.yml

