---
- hosts: gluster-backup[0]
  become: yes
  vars: 
    ansible_user: admin

  tasks:
  - name: Reverse geo-replication
    import_role:
      name: gluster
      tasks_from: initial_failback_sync.yml


